### ISSUE TITLE
Create section on MVP for Tony Award Data

### ISSUE THREAD

**Issue by nikhil-kamat** [Open-Broadway-Data/Data-Collection#14]

**Comment by ybressler** [comment]
Picking this back up.

**Comment by ybressler** [comment]
This is completed.

**Comment by ybressler** [comment]
![OBD Database ERD – 2021-02-07 13:34:33 585743](https://user-images.githubusercontent.com/40807730/107157442-1ece3f80-6952-11eb-861a-5036d116d01e.png)
